### ISSUE TITLE
Equipment page: Large image distorts the layout.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Mobile-Dewatering#142]
http://mobile-dewatering.stage.titanweb.com.au/equipment-hire/
![image](https://cloud.githubusercontent.com/assets/11186313/13309349/de61a104-dbb6-11e5-94bf-87fc47638a6a.png)

**Comment by nakul-titan** [comment]
Crop function is working fine, please try adding new fresh images as some of the images are uploaded before writing crop function due to which it is displaying full image.

**Comment by roseliesromeo** [comment]
I added new image. Though the result is different but still the images don't have the same size.
![image](https://cloud.githubusercontent.com/assets/11186313/13310644/e7b8e9b8-dbc2-11e5-8af2-709db2117c51.png)
